name: mt_mol
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cairo=1.16.0=hb05425b_5
  - cffi=1.17.1=py39h1fdaa30_1
  - comm=0.2.2=pyhd8ed1ab_1
  - debugpy=1.8.11=py39h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dftd4=3.7.0=hc15f34f_3
  - entrypoints=0.4=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - icu=73.1=h6a678d5_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.12.0=pyh41d4057_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=7.3.4=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libblas=3.9.0=31_h59b9bed_openblas
  - libcblas=3.9.0=31_he106b2a_openblas
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.78.4=hdc74915_0
  - libgomp=14.2.0=h767d61c_2
  - libiconv=1.16=h5eee18b_3
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mctc-lib=0.3.2=h3b12eaf_1
  - multicharge=0.3.0=hc15f34f_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openbabel=3.1.1=py39hee2736e_2
  - openssl=3.5.0=h7b32b05_1
  - packaging=24.2=pyhd8ed1ab_2
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py39h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prompt-toolkit=3.0.50=pyha770c72_0
  - prompt_toolkit=3.0.50=hd8ed1ab_0
  - psutil=5.9.0=py39h5eee18b_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.9.21=he870216_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=2_cp39
  - pyzmq=26.2.0=py39h6a678d5_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - simple-dftd3=1.2.1=h3b12eaf_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tblite=0.4.0=hc15f34f_1
  - tk=8.6.14=h39e8969_0
  - tmux=3.5=h4463017_0
  - toml-f=0.4.2=h3b12eaf_2
  - tornado=6.1=py39hb9d737c_3
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xtb=6.7.1=hc15f34f_2
  - xtb-python=22.1=py39h8cd3c5a_2
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==0.33.0
      - aiobotocore==2.21.1
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.10.9
      - annotated-types==0.7.0
      - anyio==4.8.0
      - array-api-compat==1.11.2
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - athina-client==0.2.5
      - attrs==25.1.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.3
      - botocore==1.37.1
      - build==1.2.2.post1
      - cachetools==5.5.2
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - cellxgene-census==1.15.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - chroma-hnswlib==0.7.6
      - chromadb==0.6.3
      - click==8.1.8
      - coloredlogs==15.0.1
      - contourpy==1.3.0
      - cssselect2==0.8.0
      - cycler==0.12.1
      - data==0.4
      - dataclasses==0.6
      - dataclasses-json==0.6.7
      - datasets==2.19.2
      - deepchem==2.8.0
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dill==0.3.8
      - distro==1.9.0
      - docarray==0.40.0
      - docker-pycreds==0.4.0
      - durationpy==0.9
      - efgs==0.8.4
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - evaluate==0.4.2
      - exceptiongroup==1.2.2
      - faiss-gpu==1.7.2
      - fastapi==0.115.11
      - fcd==1.2.2
      - filelock==3.17.0
      - filetype==1.2.0
      - fire==0.7.0
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.3.1
      - funcsigs==1.0.2
      - future==1.0.0
      - fuzzywuzzy==0.18.0
      - geodesic-interpolate==1.0.0
      - geometric==1.1
      - get-annotations==0.1.2
      - gget==0.29.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-ai-generativelanguage==0.6.16
      - google-api-core==2.24.2
      - google-auth==2.38.0
      - googleapis-common-protos==1.69.1
      - greenlet==3.1.1
      - grpcio==1.71.0
      - grpcio-status==1.71.0
      - guacamol==0.5.5
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.29.2
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - ipywidgets==8.1.6
      - jinja2==3.1.6
      - jiter==0.9.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-widgets==3.0.14
      - kiwisolver==1.4.7
      - kubernetes==32.0.1
      - langchain==0.3.23
      - langchain-chroma==0.2.2
      - langchain-community==0.3.21
      - langchain-core==0.3.51
      - langchain-deepseek==0.1.3
      - langchain-google-genai==2.0.11
      - langchain-huggingface==0.1.2
      - langchain-openai==0.3.11
      - langchain-text-splitters==0.3.8
      - langgraph==0.3.25
      - langgraph-checkpoint==2.0.24
      - langgraph-prebuilt==0.1.8
      - langgraph-sdk==0.1.61
      - langsmith==0.3.13
      - latex==0.7.0
      - legacy-api-wrap==1.4.1
      - llamaapi==0.1.36
      - llvmlite==0.43.0
      - loguru==0.7.3
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - mmh3==5.1.0
      - monotonic==1.6
      - morfeus-ml==0.7.2
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - mypy-extensions==1.0.0
      - mysql-connector-python==9.3.0
      - natsort==8.4.0
      - networkx==3.2.1
      - numba==0.60.0
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - oauthlib==3.2.2
      - onnxruntime==1.19.2
      - openai==1.69.0
      - openpyxl==3.1.5
      - opentelemetry-api==1.30.0
      - opentelemetry-exporter-otlp-proto-common==1.30.0
      - opentelemetry-exporter-otlp-proto-grpc==1.30.0
      - opentelemetry-instrumentation==0.51b0
      - opentelemetry-instrumentation-asgi==0.51b0
      - opentelemetry-instrumentation-fastapi==0.51b0
      - opentelemetry-proto==1.30.0
      - opentelemetry-sdk==1.30.0
      - opentelemetry-semantic-conventions==0.51b0
      - opentelemetry-util-http==0.51b0
      - orjson==3.10.15
      - ormsgpack==1.9.1
      - overrides==7.7.0
      - pandas==2.2.3
      - patsy==1.0.1
      - pillow==11.1.0
      - polanyi==0.0.1
      - posthog==3.19.1
      - propcache==0.3.0
      - proto-plus==1.26.1
      - protobuf==3.20.3
      - pubchempy==1.0.4
      - pyarrow==19.0.1
      - pyarrow-hotfix==0.7
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pyberny==0.6.3
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.8.1
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pypdf==5.3.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyscf==2.8.0
      - pystow==0.7.0
      - pytdc==1.1.15
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - ray==2.43.0
      - rdkit==2023.9.6
      - rdkit-pypi==2022.9.5
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - retrying==1.3.4
      - rich==13.9.4
      - rpds-py==0.23.1
      - rsa==4.9
      - s3fs==2024.3.1
      - safetensors==0.5.3
      - scanpy==1.10.3
      - scikit-learn==1.2.2
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentence-transformers==3.4.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - session-info==1.0.1
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - shutilwhich==1.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - somacore==1.0.11
      - soupsieve==2.6
      - sqlalchemy==2.0.38
      - starlette==0.46.1
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - sympy==1.13.1
      - tempdir==0.7.1
      - tenacity==9.0.0
      - termcolor==3.1.0
      - threadpoolctl==3.5.0
      - tiktoken==0.9.0
      - tiledb==0.29.1
      - tiledbsoma==1.11.4
      - tinycss2==1.4.0
      - tokenizers==0.13.3
      - tomli==2.2.1
      - torch==2.6.0
      - tqdm==4.67.1
      - transformers==4.27.0
      - triton==3.2.0
      - typer==0.15.2
      - types-requests==2.32.0.20250306
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - umap-learn==0.5.7
      - urllib3==2.4.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - wandb==0.19.8
      - watchfiles==1.0.4
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - wurlitzer==3.1.1
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.23.0